### ISSUE TITLE
Wrapping Translixir.Http.Client with HTTPoison.Base

### ISSUE THREAD

**Issue by kianmeng** [naomijub/translixir#13]
The current implementation of `Translixir.Http.Client` is using `Agent` and `HTTPoison`, is there any reasons for doing so? 

Typical HTTP client based on `HTTPoison` is implemented by wrapping `HTTPoison.Base` as recommended in the official doc, https://hexdocs.pm/httpoison/readme.html#wrapping-httpoison-base.

**Comment by naomijub** [comment]
A few reasons come to mind.
1. Last time I used Poison was prior to `HTTPoison.Base`.
2. Each http response has different field and they are in edn format
3. How does mox work with base? [mox branch](https://github.com/naomijub/translixir/tree/mox)  (there is some config problem here)
4. The Client itself doesn't actually make the HTTP calls it is just the configurations state. Maybe I should change it to `Translixir.Crux.Client`
5. Would it work well with Eden.decode?

**Comment by kianmeng** [comment]
I see.

3. Perhaps something like https://medium.com/flatiron-labs/elixir-test-mocking-with-mox-b825a955143f.
5. Mock the response as if already decoded by `Eden.decode`?

Or if you don't want to go down the `Mox` path, and want to test against the actual data, perhaps [`exvcr`](https://hex.pm/packages/exvcr) ?

**Comment by naomijub** [comment]
I used this medium to starts configuring MOX 😂.
4. Forget this topic, it was a misunderstanding from my part. 

I will take a look at `Base` soon, after I have configured MOX. Thanks

**Comment by naomijub** [comment]
Using Base as behavior for MOX https://github.com/naomijub/translixir/pull/14
